### ISSUE TITLE
Re-broadcast dialog doesn't appear

### ISSUE THREAD

**Issue by kebian** [AvilanHauxen/LFG_MatchMaker#1]
Thanks for the AddOn.  I really like it.  Just a small bug and perhaps it's just me but the re-broadcast dialog doesn't seem to pop up at all.

**Comment by kebian** [comment]
Sorry I don't have time to write an actual patch right now but I will later unless you beat me to it.  The bug is in LFGMM_LfmTab.lua on line 330.

```		-- Start broadcast
		if (LFGMM_DB.SEARCH.LFG.Broadcast) then			
			LFGMM_BroadcastWindow_StartBroadcast();
		end
```

Should instead be
```		-- Start broadcast
		if (LFGMM_DB.SEARCH.LFM.Broadcast) then			
			LFGMM_BroadcastWindow_StartBroadcast();
		end
```

i.e. the LFG should be LFM.

**Comment by AvilanHauxen** [comment]
Thank you for bringing this issue to my attention.
I have updated the code and this issue should now be fixed.
