### ISSUE TITLE
Raids beyond Onyxia's Lair do not appear in list in the interface

### ISSUE THREAD

**Issue by wiesshund** [AvilanHauxen/LFG_MatchMaker#10]
Raids beyond Onyxia's Lair do not appear in list in the interface

I see them in the variables LUA file
but in game, when you bring up the UI, Ony is the last raid you can choose
even BWL does not show up

**Comment by wiesshund** [comment]
Ok you can sort of close this
I enabled them in the LUA, so you just had them commented out.
May be worth updating though? BWL is out, and it will avoid you having to update again later?

**Comment by AvilanHauxen** [comment]
Originally I planed to enable new raids as they were released, but have lately been unable to find time to update the project and was therefore a bit late to enable BWL.

I have now enabled all the raids in version 1.0.6.

**Comment by wiesshund** [comment]
Cool.
I had enabled them, i suppose i could have contributed it, but i did not want to step on someone else's stuff
