### ISSUE TITLE
Unable to click ignore button with new update

### ISSUE THREAD

**Issue by wiesshund** [AvilanHauxen/LFG_MatchMaker#15]
The button bumps up and down, but the notification window does not go away.
Only way to get rid of it is to click stop search

the whisper and request invite buttons do work

**Comment by wiesshund** [comment]
and now it wants to work
if it does it again, i will see if it trips a lua error

**Comment by wiesshund** [comment]
I found it, kinda but no LUA error

If type found is unknown (shows red question mark rather than LFG or LFM)
the ignore button does not click.
If type found is LFG or LFM it works fine.

**Comment by wiesshund** [comment]
exact text player said that triggered this was
"Need 1 for UD Strat DPS"

**Comment by AvilanHauxen** [comment]
This issue should now be fixed in v1.0.7
